---
# cluster_name is used to group the nodes in a folder within VirtualBox:
cluster_name: Kubernetes Cluster
# Uncomment to set environment variables for services such as crio and kubelet.
# For example, configure the cluster to pull images via a proxy.
# environment: |
#   HTTP_PROXY=http://my-proxy:8000
#   HTTPS_PROXY=http://my-proxy:8000
#   NO_PROXY=127.0.0.1,localhost,master-node,node01,node02,node03
# All IPs/CIDRs should be private and allowed in /etc/vbox/networks.conf.
network:
  # IPs are simply incremented from the control IP, starting with 11, 21 and 51
  control_ip: 10.0.0.10
  node_ip: 10.0.0.20
  nfs_ip: 10.0.0.50
  domain: example.com
  dns_servers:
    - 8.8.8.8
    - 8.8.4.4
  pod_cidr: 172.16.1.0/16
  service_cidr: 172.17.1.0/18
nodes:
  control:
    count: 2
    cpu: 2
    memory: 4096
    name: controller0
  workers:
    count: 0
    cpu: 1
    memory: 4096
    name: node0
nfs:
  count: 0
  cpu: 1
  memory: 1024
  name: nfs0
  storage_size: 5120 
  dir: /nfs/exports/myshare
ansible: 
# ansible will be always deployed on control node 1
  version: 2.9.15
# Mount additional shared folders from the host into each virtual machine.
# Note that the project directory is automatically mounted at /vagrant.
# shared_folders:
#   - host_path: ../images
#     vm_path: /vagrant/images
software:
  #box: generic/rhel8
  box: bento/centos-stream-8
  calico: 3.26.0
  # To skip the dashboard installation, set its version to an empty value or comment it out:
  dashboard: 2.7.0
  kubernetes: 1.28.0-*
  os: Centos8
  etcdutl: 3.5.6
